/**
 * Created by lenovo on 2018/9/1.
 */
$(function(){
    $(".change-pic").find("img").hover(
        function(){
            $(this).attr("src","img/icon/turnfly3921_xxx1206.png");
        },
        function(){
            $(this).attr("src","img/icon/turnfly3921_1xxx1206.png");
        }
    )
    $(".small-lione").click(function(e){
        //event.stopPropagation();
        event.cancelBubble=true;
        //$(".up-trian").css("display","none");
        //$(".down-trian").css("display","block");
        $(this).find("a").find(".up-trian").toggle();
        $(this).find("a").find(".down-trian").toggle();
        $(".onesec-lione").toggle();
        $(".onelist-litwo").css("display","none");
        $(".onelist-lithree").css("display","none");
        $(".onelist-lifour").css("display","none");
        $(".onelist-lifive").css("display","none");
        $(".sectwo-lione").css("display","none");
        $(".sectwo-litwo").css("display","none");
        $(".sectwo-lithree").css("display","none");
        $(".sectwo-lifour").css("display","none");
        $(".sectwo-lifive").css("display","none");
    })
    $(".small-litwo").click(function(e){
        //event.stopPropagation();
        event.cancelBubble=true;
        $(this).find("a").find(".up-trian").toggle();
        $(this).find("a").find(".down-trian").toggle();
        $(".onesec-litwo").toggle();
        $(".onelist-lione").css("display","none");
        $(".onelist-lithree").css("display","none");
        $(".onelist-lifour").css("display","none");
        $(".onelist-lifive").css("display","none");
        $(".sectwo-lione").css("display","none");
        $(".sectwo-litwo").css("display","none");
        $(".sectwo-lithree").css("display","none");
        $(".sectwo-lifour").css("display","none");
        $(".sectwo-lifive").css("display","none");
    })




    $(".lione11").find("li").click(function(e){
        event.cancelBubble=true;
        var listCont=$(this).html();
        $(".small-lione").find("a").find(".smallone-cont").html(listCont);
        $(".small-li").find("a").find(".up-trian").css("display","none");
        $(".small-li").find("a").find(".down-trian").css("display","block");
        $(".onesec-lione").css("display","none");
    })
    $(".litwo22").find("li").click(function(e){
        event.cancelBubble=true;
        var listCont=$(this).html();
        $(".small-litwo").find("a").find(".smalltwo-cont").html(listCont);
        $(".small-litwo").find("a").find(".up-trian").css("display","none");
        $(".small-litwo").find("a").find(".down-trian").css("display","block");
        $(".onesec-litwo").css("display","none");
    })

    $(".middle-inputone").click(function(e){
        //event.stopPropagation();
        event.cancelBubble=true;
        $(".onelist-lithree").css("display","block");
        $(".onelist-lione").css("display","none");
        $(".onelist-litwo").css("display","none");
        $(".onelist-lifour").css("display","none");
        $(".onelist-lifive").css("display","none");
        $(".sectwo-lithree").css("display","none");
        $(".sectwo-lifour").css("display","none");
        $(".sectwo-lifive").css("display","none");
    })
    $(".middle-inputtwo").click(function(e){
        //event.stopPropagation();
        event.cancelBubble=true;
        $(".onelist-lifour").css("display","block");
        $(".onelist-lione").css("display","none");
        $(".onelist-litwo").css("display","none");
        $(".onelist-lithree").css("display","none");
        $(".onelist-lifive").css("display","none");
        $(".sectwo-lithree").css("display","none");
        $(".sectwo-lifour").css("display","none");
        $(".sectwo-lifive").css("display","none");
    })
    $(".onelist-lithree").click(function(){
        //event.stopPropagation();
        event.cancelBubble=true;
    })
    $(".onelist-lifour").click(function(){
        //event.stopPropagation();
        event.cancelBubble=true;
    })
    $(".lithree-close-three").click(function(){
        $(".onelist-lithree").css("display","none");
    })
    $(".lithree-close-four").click(function(){
        $(".onelist-lifour").css("display","none");
    })
    $(".lithree-two-three").find("li").click(function(){
        var liCont=$(this).html();
        $(".middle-inputone").val(liCont);
        $(".onelist-lithree").css("display","none");
    })
    $(".lithree-two-four").find("li").click(function(){
        var liCont=$(this).html();
        $(".middle-inputtwo").val(liCont);
        $(".onelist-lifour").css("display","none");
    })
    $(".chufa-li").click(function(){
        $(".onelist-lione").css("display","none");
        $(".onelist-litwo").css("display","none");
        $(".onelist-lithree").css("display","none");
        $(".onelist-lifour").css("display","none");
        $(".onelist-lifive").css("display","none");
        $(".sectwo-lithree").css("display","none");
        $(".sectwo-lifour").css("display","none");
        $(".sectwo-lifive").css("display","none");
    })



    $(".sectwo-left-list").find("li").hover(
        function(){
            $(this).find(".right-arrow").css("display","none");
            $(this).find(".left-arrow").css("display","inline");
            $(this).css("border-right","none");
            $(this).find(".sectwo-left-lione").css("display","block");
        },
        function(){
            $(this).find(".right-arrow").css("display","inline");
            $(this).find(".left-arrow").css("display","none");
            $(this).css("border-right","1px solid #ccc");
            $(".sectwo-left-lione-list").find("li").css("border-right","none");
            $(this).find(".sectwo-left-lione").css("display","none");
        }
    )
    $(".sectwo-left-lione").find("li").hover(
        function(){
            $(this).css("background-color","#fff1cc");
        },
        function(){
            $(this).css("background-color","#fff");
        }
    )
    $(".right-lunbo").find("li").hover(
        function(){
            $(".right-lunbo").find("li").removeClass("lunboli-acitve");
            $(this).addClass("lunboli-acitve");
        },
        function(){
            $(".right-lunbo").find("li").removeClass("lunboli-acitve");
            $(this).removeClass("lunboli-acitve");
        }
    )
    $(".secright-two-lione").click(function(){
        //event.stopPropagation();
        event.cancelBubble=true;
        $(this).find("a").find(".up-trian").toggle();
        $(this).find("a").find(".down-trian").toggle();
        $(".sectwo-lione").toggle();
        $(".onesec-lione").css("display","none");
        $(".onelist-litwo").css("display","none");
        $(".onelist-lithree").css("display","none");
        $(".onelist-lifour").css("display","none");
        $(".onelist-lifive").css("display","none");
        $(".sectwo-lithree").css("display","none");
        $(".sectwo-lifour").css("display","none");
        $(".sectwo-lifive").css("display","none");
    })
    $(".sectwo-rightone").find("li").click(function(e){
        var listCont=$(this).html();
        $(".secright-two-lione").find("a").find(".smallone-cont").html(listCont);
    })
    $(".secright-two-litwo").click(function(){
        //event.stopPropagation();
        event.cancelBubble=true;
        $(this).find("a").find(".up-trian").toggle();
        $(this).find("a").find(".down-trian").toggle();
        $(".sectwo-litwo").toggle();
        $(".onelist-lione").css("display","none");
        $(".onesec-litwo").css("display","none");
        $(".onelist-lithree").css("display","none");
        $(".onelist-lifour").css("display","none");
        $(".onelist-lifive").css("display","none");
        $(".sectwo-lithree").css("display","none");
        $(".sectwo-lifour").css("display","none");
        $(".sectwo-lifive").css("display","none");
    })
    $(".sectwo-righttwo").find("li").click(function(e){
        var listCont=$(this).html();
        $(".secright-two-litwo").find("a").find(".smalltwo-cont").html(listCont);
    })
    $(".secright-two-lithree").click(function(){
        //event.stopPropagation();
        event.cancelBubble=true;
        $(this).find("a").find(".up-trian").toggle();
        $(this).find("a").find(".down-trian").toggle();
        $(".sectwo-lithree").toggle();
        $(".onelist-lione").css("display","none");
        $(".onelist-litwo").css("display","none");
        $(".onelist-lithree").css("display","none");
        $(".onelist-lifour").css("display","none");
        $(".onelist-lifive").css("display","none");
        $(".sectwo-lifour").css("display","none");
        $(".sectwo-lifive").css("display","none");
    })
    $(".sectwo-rightthree").find("li").click(function(e){
        var listCont=$(this).html();
        $(".secright-two-lithree").find("a").find(".smallthree-cont").html(listCont);
        $(".sectwo-lithree").css("display","none");
        $(".small-li").find("a").find(".up-trian").css("display","none");
        $(".small-li").find("a").find(".down-trian").css("display","block");
    })
    $(".secright-two-lifour").click(function(){
        //event.stopPropagation();
        event.cancelBubble=true;
        $(this).find("a").find(".up-trian").toggle();
        $(this).find("a").find(".down-trian").toggle();
        $(".sectwo-lifour").toggle();
        $(".onelist-lione").css("display","none");
        $(".onelist-litwo").css("display","none");
        $(".onelist-lithree").css("display","none");
        $(".onelist-lifour").css("display","none");
        $(".onelist-lifive").css("display","none");
        $(".sectwo-lithree").css("display","none");
        $(".sectwo-lifive").css("display","none");
    })
    $(".sectwo-rightfour").find("li").click(function(e){
        var listCont=$(this).html();
        $(".secright-two-lifour").find("a").find(".smallfour-cont").html(listCont);
        $(".sectwo-lifour").css("display","none");
        $(".small-li").find("a").find(".up-trian").css("display","none");
        $(".small-li").find("a").find(".down-trian").css("display","block");
    })
    $(".secright-two-lifive").click(function(){
        //event.stopPropagation();
        event.cancelBubble=true;
        $(this).find("a").find(".up-trian").toggle();
        $(this).find("a").find(".down-trian").toggle();
        $(".sectwo-lifive").toggle();
        $(".onelist-lione").css("display","none");
        $(".onelist-litwo").css("display","none");
        $(".onelist-lithree").css("display","none");
        $(".onelist-lifour").css("display","none");
        $(".onelist-lifive").css("display","none");
        $(".sectwo-lithree").css("display","none");
        $(".sectwo-lifour").css("display","none");
    })
    $(".sectwo-rightfive").find("li").click(function(e){
        var listCont=$(this).html();
        $(".secright-two-lifive").find("a").find(".smallfive-cont").html(listCont);
        $(".sectwo-lifive").css("display","none");
        $(".small-li").find("a").find(".up-trian").css("display","none");
        $(".small-li").find("a").find(".down-trian").css("display","block");
    })

    $(".onesec-list").find("li").click(function(){
        $(".onesec-list").find("li").not(this).find("a").find(".up-trian").css("display","none");
        $(".onesec-list").find("li").not(this).find("a").find(".down-trian").css("display","block");
    })

    $(document).click(function(){
        $(".small-li").find("a").find(".up-trian").css("display","none");
        $(".small-li").find("a").find(".down-trian").css("display","block");
        $(".onelist-lione").css("display","none");
        $(".onelist-litwo").css("display","none");
        $(".onelist-lithree").css("display","none");
        $(".onelist-lifour").css("display","none");
        $(".onelist-lifive").css("display","none");
        $(".sectwo-lithree").css("display","none");
        $(".sectwo-lifour").css("display","none");
        $(".sectwo-lifive").css("display","none");
    })
    $(".rightthree-cont-lastli").click(function(){
        $(this).find(".bookticket").toggle();
        $(this).find(".closebook").toggle();
        $(this).parents(".rightthree-cont").next().toggle();
    })
    $(".ticket-detail").find("li").hover(
        function(){
            $(this).css("background-color","#fff1cc");
        },
        function(){
            $(this).css("background-color","#fff");
        }
    )
    $(document).scroll(function(e){
        //console.log(document.documentElement.scrollTop||document.body.scrollTop);
        var scrollT=document.documentElement.scrollTop||document.body.scrollTop;
        if(scrollT>124){
            $(".fixed-list").addClass("fixed-list-active");
        }
        else{
            $(".fixed-list").removeClass("fixed-list-active");
        }
    })



})
